---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install various macports
    community.general.macports:
      name: "{{ ports }}"
    vars:
      ports:
      - wget
      - htop
      - nmap
      - coreutils
      - ImageMagick7
      - ffmpeg
      - yt-dlp
      - gnupg2
      - tree
      - inetutils
      - go

  - name: users | mr | copy dotfiles
    tags: dotfiles,zsh
    copy:
      src: files/{{ item.src }}
      dest: /Users/mr/{{ item.dest }}
      owner: mr
      group: staff
      mode: 0600
    with_items:
      - { src: 'mac/aliases', dest: '.aliases' }
      - { src: 'mac/zshrc', dest: '.zshrc' }

  - name: configure mac settings
    osx_defaults:
      domain: com.apple.finder
      key: _FXShowPosixPathInTitle
      type: bool
      value: true
      state: present 
