---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install various macports
    community.general.macports:
      name: "{{ ports }}"
    vars:
      ports:
      - wget
      - htop
      - nmap
      - coreutils
      - ImageMagick7
      - ffmpeg
