---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Update Macports and the ports tree
    community.general.macports:
      selfupdate: true
      upgrade: true

  - name: install various macports
    community.general.macports:
      name: "{{ ports }}"
    vars:
      ports:
      - wget
      - htop
      - nmap
      - coreutils
      - ImageMagick7
      - ffmpeg
      - yt-dlp
      - gnupg2
      - tree
      - inetutils
      - tmux
      - pandoc
      - lynx
      - emacs
      - aspell
      - mtr
      - mc
      - neofetch
      - texlive-latex-extra
      - bat
      - neovim
      - rclone
      - 7zip
      - php83
      - certbot
      - ruby33
      - rbenv

  - name: users | mr | copy dotfiles
    tags: dotfiles,zsh
    copy:
      src: files/{{ item.src }}
      dest: /Users/mr/{{ item.dest }}
      owner: mr
      group: staff
      mode: 0600
    with_items:
      - { src: 'mac/aliases', dest: '.aliases' }
      - { src: 'mac/zshrc', dest: '.zshrc' }

  - name: configure screenshots folder
    community.general.osx_defaults:
      domain: com.apple.screencapture
      key: location
      type: string
      value: /Users/mr/Downloads
    become_user: mr

  - name: Avoid creating .DS_Store files on network volumes
    community.general.osx_defaults:
      domain: com.apple.desktopservices
      key: DSDontWriteNetworkStores
      type: bool
      value: true
    become_user: mr

  - name: Disable system notifications
    community.general.osx_defaults:
      path: /Library/Preferences/.GlobalPreferences
      domain: NSUserNotificationCenter
      key: enabled
      value: false
  
  - name: create lazyvim config directory for nvim
    file:
      path: ~/.config/nvim
      state: directory
      mode: '0755'
    become_user: mr

  - name: clone lazyvim repo
    git:
      repo: 'https://github.com/LazyVim/starter'
      dest: ~/.config/nvim
    become_user: mr

  - name: copy colorscheme lua file
    copy:
      src: files/mac/colorscheme.lua
      dest: /Users/mr/.config/nvim/lua/plugins/colorscheme.lua
      owner: mr
      group: staff
  
  - name: Set default Terminal font size
    community.general.osx_defaults:
      domain: com.apple.Terminal
      key: "Window Settings"
      subkey: "Basic"
      type: dict
      value:
        FontSize: 14



