---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install various macports
    community.general.macports:
      name: "{{ ports }}"
    vars:
      ports:
      - wget
      - htop
      - nmap
      - coreutils
      - ImageMagick7
      - ffmpeg
      - yt-dlp
      - gnupg2
      - tree
      - inetutils
      - go

  - name: users | mr | copy dotfiles
    tags: dotfiles,zsh
    copy:
      src: files/{{ item.src }}
      dest: /Users/mr/{{ item.dest }}
      owner: mr
      group: staff
      mode: 0600
    with_items:
      - { src: 'mac/aliases', dest: '.aliases' }
      - { src: 'mac/zshrc', dest: '.zshrc' }

  - name: configure screenshots folder
    community.general.osx_defaults:
      domain: com.apple.screencapture
      key: location
      type: string
      value: /Users/mr/Downloads
    become_user: mr

  - name: Avoid creating .DS_Store files on network volumes
    community.general.osx_defaults:
      domain: com.apple.desktopservices
      key: DSDontWriteNetworkStores
      type: bool
      value: true
    become_user: mr

  - name: Change finder default view. other view modes. `icnv`, `Nlsv`, `clmv`, `Flwv`
    community.general.osx_defaults:
      domain: com.apple.finder
      key: FXPreferredViewStyle
      type: string
      value: "Nlsv"
    become_user: mr

