# aliases
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias back='cd $OLDPWD'
alias c='clear'
alias cd..='cd ..'
alias cp='cp -iv'
alias chmod="chmod -c"
alias chmod="chmod -c"
alias df='df -h -x squashfs -x tmpfs -x devtmpfs'
alias diff='colordiff'
alias egrep='egrep --colour=auto'
alias e="vim -O "
alias E="vim -o "
alias extip='curl icanhazip.com'
alias grep='grep --color=auto'
alias l.=' ls -lhFa --time-style=long-iso --color=auto'
alias ll=' ls'
alias ls=' ls -lhF --time-style=long-iso --color=auto'
alias lsmount='mount |column -t'
#creates necessary parent directories
alias mkdir='mkdir -pv'
alias ports='netstat -tulanp'
alias h='history'
alias j='jobs -l'
alias mv='mv -iv'
alias speedtest='curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -'
#ssha will set so only need to enter ssh key passhprase once during the terminal session.
alias ssha='eval $(ssh-agent) && ssh-add'
alias svim='sudo vim'
alias tn=' tmux new -s'
alias weather='curl wttr.in'
alias hgrep='history | grep'
alias meminfo="free -m -l -t"

## get top process eating memory
alias memHog='ps auxf | sort -nr -k 4 | head -10'

## get top process eating cpu ##
alias cpuHog='ps auxf | sort -nr -k 3 | head -10'

## List largest directories (aka "ducks")
alias dirHog='du -cksh * | sort -hr | head -n 10'

# Safetynets
# do not delete / or prompt if deleting more than 3 files at a time #
alias rm='rm -I --preserve-root'

# Parenting changing perms on / #
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'


# Manage packages easier
if [ -f /usr/bin/apt ]; then
  alias update='sudo apt update'
  alias upgrade='sudo apt update && sudo apt dist-upgrade && sudo apt autoremove && sudo apt clean'
  alias install='sudo apt install'
fi

if [ -f /usr/bin/pacman ]; then
  alias update='sudo pacman -Syyy'
  alias upgrade='sudo pacman -Syu'
  alias install='sudo pacman -S'
fi

# Git Aliases
alias ga="git add ."
alias gp="git push origin main"
alias gs="git status"

# Stop after sending count ECHO_REQUEST packets #
alias ping='ping -c 5'
# Do not wait interval 1 second, go fast #
alias fastping='ping -c 100 -s.2'

## resume wget by default ##
alias wget='wget -c'

# Docker Aliases
alias dl="sudo docker ps -l -q"
alias dps="sudo docker ps"
alias di="sudo docker images"
alias dip="sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}'"
alias dkd="sudo docker run -d -P"
alias dki="sudo docker run -i -t -P"
alias dex="sudo docker exec -i -t"

# System Aliases
alias reboot="sudo /sbin/reboot"
alias shutdown="sudo /sbin/shutdown"

# Get details of a process
alias paux='ps aux | grep'

#Grabs the disk usage in the current directory
alias usage='du -ch | grep total'

# Gets the total disk usage on your machine
alias totalusage='df -hl --total | grep total'

#Shows the individual partition usages without the temporary memory values
alias partusage='df -hlT --exclude-type=tmpfs --exclude-type=devtmpfs'

# Gives you what is using the most space. Both directories and files. Varies on current directory
alias most='du -hsx * | sort -rh | head -10'

# reload bash config
alias reload="source ~/.bashrc"
