# Nicer prompt.
#export PS1=$'\n'"%F{green} %@%F %3~ %F{white}"$'\n'"$ "
export PS1=$'\n'"%F{green}🍩%@ %W%F %F{yellow} %M %~ %F %F{white}"$'\n'"$ "
#tty -s && export PS1="\[\033[38;5;35m\]\t [\[\033[38;5;33m\]\j\[\033[38;5;35m\]] [\h:\[$(tput sgr0)\]\[\033[38;5;33m\]\w\[$(tput setaf 3)\]\[\033[38;5;35m\]]\n\\[\033[38;5;35m\]☕ \[$(tput sgr0)\]"


# Custom $PATH with extra locations.
export PATH=$HOME/Library/Python/3.9/bin:/usr/local/bin:/usr/local/sbin:$HOME/bin:/usr/local/git/bin:$HOME/.composer/vendor/bin:$PATH

# Include alias file (if present) containing aliases for ssh, etc.
if [ -f ~/.aliases ]
then
  source ~/.aliases
fi

# Show system information at login
if [ -t 0 ]; then
    if type -p "neofetch" > /dev/null; then
        neofetch
    else
        echo "Warning: neofetch was called, but it's not installed."
    fi
fi



